#include "nsISupports.idl"
#include "rhITrayWindNotify.idl" 
interface nsIBaseWindow;

[scriptable,uuid(18100a23-0e0f-4201-8378-c9625d09be39)]

interface rhITray: nsISupports
{
    void    add(in nsIBaseWindow aWindow);
    void    remove(in nsIBaseWindow aWindow);
    void    hide(in nsIBaseWindow aWindow);
    void    show(in nsIBaseWindow aWindow);

    void    hideall();
    void    showall();
    boolean isInitializedAlready(); 
    void    sendnotification(in string aTitle, in string aMessage,in unsigned long aSeverity,in unsigned long aTimeout,in string aIcon);

    void    settooltipmsg(in string aMessage);
    void    seticonimage(in string aIcon);

    void    hideicon();
    void    showicon();

    void    setwindnotifycallback(in rhITrayWindNotify jsNotify);
    void    unsetwindnotifycallback(in rhITrayWindNotify jsNotify);
    void    setmenuitemtext(in unsigned long aIndex, in string aText);

    

};

